.TH MKLIBS 1 2002-07-07 Debian "Debian User's Manual"
.SH NAME
mklibs-small \- make a minimal set of libraries
.SH SYNOPSIS
\fBmklibs-small\fR [\fIOPTION\fR]... \fB-d \fIDESTINATION FILE\fR...
.SH DESCRIPTION
Place the minimal set of libraries required by
.IR FILE (s)
in
.IR DESTINATION .
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-no\-default\-lib\fR
Omit the default library path.
.TP
\fB\-d \fIDESTINATION\fR, \fB\-\-dest\-dir\fI DESTINATION
Place the libraries in \fIDESTINATION\fR.
.TP
\fB\-L \fILIBDIR\fR[\fB:\fILIBDIR\fR]...
Prepend \fILIBDIR\fR(s) to the library search path.
.TP
\fB\-\-ldlib \fILDLIB
Use \fILDLIB\fR for the dynamic linker.
.TP
\fB\-\-libc\-extras\-dir \fIEXTRADIR
Use \fIEXTRADIR\fR to find extra libc files.
.TP
\fB\-v\fR, \fB\-\-verbose
Explain what is being done.
.TP
\fB\-h\fR, \fB\-\-help
Display help and exit.
.SH AUTHOR
This manual page was written by Matt Kraai.
