.TH MKLIBS 1 2002-07-07 Debian "Debian User's Manual"
.SH NAME
mklibs \- make a minimal set of libraries
.SH SYNOPSIS
\fBmklibs\fR [\fIOPTION\fR]... \fB-d \fIDESTINATION FILE\fR...
.SH DESCRIPTION
Place the minimal set of libraries required by
.IR FILE (s)
in
.IR DESTINATION .
.SH OPTIONS
.TP
\fB\-d \fIDESTINATION\fR, \fB\-\-dest\-dir\fI DESTINATION
Place the libraries in \fIDESTINATION\fR.
.TP
\fB\-D\fR, \fB\-\-no\-default\-lib\fR
Omit the default library path.
.TP
\fB\-L \fILIBDIR\fR[\fB:\fILIBDIR\fR]...
Prepend \fILIBDIR\fR(s) to the library search path.
.TP
\fB\-\-ldlib \fILDLIB
Use \fILDLIB\fR for the dynamic linker.
.TP
\fB\-\-libc\-extras\-dir \fIEXTRADIR
Use \fIEXTRADIR\fR to find extra libc files.
.TP
\fB\-\-target \fITARGET
Prepend \fITARGET\fB\-\fR to the gcc and binutils calls.
.TP
\fB\-\-root \fIROOT
Search in \fIROOT\fB\-\fR for library rpaths.
.TP
\fB\-\-sysroot \fISYSROOT
Locate libraries and associated files relative to \fISYSROOT\fR.
.TP
\fB\-\-gcc\-options \fIOPTIONS
Pass \fIOPTIONS\fR to the compiler when relinking.
.TP
\fB\-\-libdir \fIDIR
Use \fIDIR\fR (for example, \fBlib64\fR) in place of \fBlib\fR in
default library paths.
.TP
\fB\-v\fR, \fB\-\-verbose
Explain what is being done.
.TP
\fB\-h\fR, \fB\-\-help
Display help and exit.
.SH BUGS
\fBmklibs\fR does not support the
\fB\-\-dry\-run\fR and \fB\-\-version\fR options
supported by \fBmklibs.sh\fR.
.SH AUTHOR
This manual page was written by Matt Kraai.
