/*
 * buildopts.h 
 * Automatically generated
 */

#define LOADABLE_MODULES 1
#define AST_MODULE_CHAN_LOCAL 1
#define AST_MODULE_APP_VOICEMAIL 1
#define AST_MODULE_APP_CONFBRIDGE 1
#define AST_MODULE_RES_MONITOR 1
#define AST_MODULE_RES_AGI 1
#define AST_MODULE_RES_ADSI 1
#define AST_MODULE_RES_SMDI 1
#define AST_MODULE_RES_ODBC 1
#define AST_MODULE_RES_CRYPTO 1
#define AST_MODULE_RES_HTTP_WEBSOCKET 1
#define AST_MODULE_RES_PKTCCOPS 1
#define AST_MODULE_RES_AEL_SHARE 1
#define AST_MODULE_G711_NEW_ALGORITHM 1
#define AST_BUILDOPT_SUM "63f1ab29b67970897dabf7f3ceb2d086"
#define AST_BUILDOPTS "LOADABLE_MODULES"
