# CMake generated Testfile for 
# Source directory: /home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests
# Build directory: /home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(CMake.List "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/ListTest.cmake")
ADD_TEST(CMake.VariableWatch "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/VariableWatchTest.cmake")
ADD_TEST(CMake.Include "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/IncludeTest.cmake")
ADD_TEST(CMake.FindBase "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/FindBaseTest.cmake")
ADD_TEST(CMake.Toolchain "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/ToolchainTest.cmake")
ADD_TEST(CMake.GetFilenameComponentRealpath "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
ADD_TEST(CMake.Version "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/VersionTest.cmake")
ADD_TEST(CMake.Message "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/MessageTest.cmake")
ADD_TEST(CMake.File "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/FileTest.cmake")
ADD_TEST(CMake.ConfigureFile "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/ConfigureFileTest.cmake")
ADD_TEST(CMake.SeparateArguments "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/SeparateArgumentsTest.cmake")
ADD_TEST(CMake.ImplicitLinkInfo "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
ADD_TEST(CMake.ModuleNotices "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/ModuleNoticesTest.cmake")
ADD_TEST(CMake.GetProperty "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/GetPropertyTest.cmake")
ADD_TEST(CMake.If "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/IfTest.cmake")
ADD_TEST(CMake.String "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/StringTest.cmake")
ADD_TEST(CMake.Math "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/MathTest.cmake")
ADD_TEST(CMake.CMakeMinimumRequired "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
ADD_TEST(CMake.CompilerIdVendor "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/CompilerIdVendorTest.cmake")
ADD_TEST(CMake.ProcessorCount "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DKWSYS_TEST_EXE=/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Source/kwsys/cmsysTestsCxx" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/ProcessorCountTest.cmake")
ADD_TEST(CMake.PushCheckState "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/PushCheckStateTest.cmake")
ADD_TEST(CMake.While "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/WhileTest.cmake")
ADD_TEST(CMake.CMakeHostSystemInformation "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/CMakeHostSystemInformationTest.cmake")
ADD_TEST(CMake.FileDownload "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/FileDownloadTest.cmake")
SET_TESTS_PROPERTIES(CMake.FileDownload PROPERTIES  PASS_REGULAR_EXPRESSION "file already exists with expected MD5 sum")
ADD_TEST(CMake.FileUpload "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/FileUploadTest.cmake")
ADD_TEST(CMake.ELF "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/ELFTest.cmake")
ADD_TEST(CMake.EndStuff "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-Ddir:STRING=/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/EndStuffTest" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/EndStuffTest.cmake")
ADD_TEST(CMake.GetPrerequisites "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DCTEST_CONFIGURATION_TYPE:STRING=\${CTEST_CONFIGURATION_TYPE}" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/GetPrerequisitesTest.cmake")
ADD_TEST(CMake.CheckSourceTree "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/bin/cmake" "-DCMake_BINARY_DIR:PATH=/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2" "-DCMake_SOURCE_DIR:PATH=/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-DHOME:STRING=/home/alter0ne" "-P" "/home/alter0ne/rtk_openwrt_sdk/build_dir/host/cmake-2.8.12.2/Tests/CMakeTests/CheckSourceTreeTest.cmake")
