/* valaccodeidentifier.c generated by valac, the Vala compiler
 * generated from valaccodeidentifier.vala, do not modify */

/* valaccodeidentifier.vala
 *
 * Copyright (C) 2006  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include "valaccode.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define _g_free0(var) (var = (g_free (var), NULL))

struct _ValaCCodeIdentifierPrivate {
	gchar* _name;
};

static gint ValaCCodeIdentifier_private_offset;
static gpointer vala_ccode_identifier_parent_class = NULL;

static void vala_ccode_identifier_real_write (ValaCCodeNode* base,
                                       ValaCCodeWriter* writer);
static void vala_ccode_identifier_finalize (ValaCCodeNode * obj);

static inline gpointer
vala_ccode_identifier_get_instance_private (ValaCCodeIdentifier* self)
{
	return G_STRUCT_MEMBER_P (self, ValaCCodeIdentifier_private_offset);
}

ValaCCodeIdentifier*
vala_ccode_identifier_construct (GType object_type,
                                 const gchar* _name)
{
	ValaCCodeIdentifier* self = NULL;
	g_return_val_if_fail (_name != NULL, NULL);
	self = (ValaCCodeIdentifier*) vala_ccode_expression_construct (object_type);
	vala_ccode_identifier_set_name (self, _name);
	return self;
}

ValaCCodeIdentifier*
vala_ccode_identifier_new (const gchar* _name)
{
	return vala_ccode_identifier_construct (VALA_TYPE_CCODE_IDENTIFIER, _name);
}

static void
vala_ccode_identifier_real_write (ValaCCodeNode* base,
                                  ValaCCodeWriter* writer)
{
	ValaCCodeIdentifier * self;
	const gchar* _tmp0_;
	self = (ValaCCodeIdentifier*) base;
	g_return_if_fail (writer != NULL);
	_tmp0_ = self->priv->_name;
	vala_ccode_writer_write_string (writer, _tmp0_);
}

const gchar*
vala_ccode_identifier_get_name (ValaCCodeIdentifier* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}

void
vala_ccode_identifier_set_name (ValaCCodeIdentifier* self,
                                const gchar* value)
{
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp0_;
}

static void
vala_ccode_identifier_class_init (ValaCCodeIdentifierClass * klass,
                                  gpointer klass_data)
{
	vala_ccode_identifier_parent_class = g_type_class_peek_parent (klass);
	((ValaCCodeNodeClass *) klass)->finalize = vala_ccode_identifier_finalize;
	g_type_class_adjust_private_offset (klass, &ValaCCodeIdentifier_private_offset);
	((ValaCCodeNodeClass *) klass)->write = (void (*) (ValaCCodeNode*, ValaCCodeWriter*)) vala_ccode_identifier_real_write;
}

static void
vala_ccode_identifier_instance_init (ValaCCodeIdentifier * self,
                                     gpointer klass)
{
	self->priv = vala_ccode_identifier_get_instance_private (self);
}

static void
vala_ccode_identifier_finalize (ValaCCodeNode * obj)
{
	ValaCCodeIdentifier * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_TYPE_CCODE_IDENTIFIER, ValaCCodeIdentifier);
	_g_free0 (self->priv->_name);
	VALA_CCODE_NODE_CLASS (vala_ccode_identifier_parent_class)->finalize (obj);
}

/**
 * Represents a identifier in the C code.
 */
GType
vala_ccode_identifier_get_type (void)
{
	static volatile gsize vala_ccode_identifier_type_id__volatile = 0;
	if (g_once_init_enter (&vala_ccode_identifier_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValaCCodeIdentifierClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_ccode_identifier_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaCCodeIdentifier), 0, (GInstanceInitFunc) vala_ccode_identifier_instance_init, NULL };
		GType vala_ccode_identifier_type_id;
		vala_ccode_identifier_type_id = g_type_register_static (VALA_TYPE_CCODE_EXPRESSION, "ValaCCodeIdentifier", &g_define_type_info, 0);
		ValaCCodeIdentifier_private_offset = g_type_add_instance_private (vala_ccode_identifier_type_id, sizeof (ValaCCodeIdentifierPrivate));
		g_once_init_leave (&vala_ccode_identifier_type_id__volatile, vala_ccode_identifier_type_id);
	}
	return vala_ccode_identifier_type_id__volatile;
}

