%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContextExt_InvalidAddress
%% Source: /net/isildur/ldisk/daily_build/r16b02_prebuild_opu_o.2013-09-16_20/otp_src_R16B02/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContextExt_InvalidAddress').
-ic_compiled("4_3_3").


-include("CosNaming_NamingContextExt.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContextExt/InvalidAddress:1.0",
                   "InvalidAddress",[]}.

%% returns id
id() -> "IDL:omg.org/CosNaming/NamingContextExt/InvalidAddress:1.0".

%% returns name
name() -> "CosNaming_NamingContextExt_InvalidAddress".



