#!/bin/sh
#
# Time the functions.
#
SYSBC=/usr/bin/bc
if [ x$BC = x ] ; then
  BC=../bc/bc
fi
for file in exp.b ln.b sine.b atan.b jn.b mul.b div.b raise.b sqrt.b fact.b
do
for prog in $SYSBC $BC $OTHERBC
do
echo Timing $file with $prog
time $prog -l $file
done
done
