#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BACKPORT_AVERAGE 1
#define CPTCFG_BACKPORT_LEDS_TRIGGERS 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_NL80211_TESTMODE 1
#define CPTCFG_CFG80211_CERTIFICATION_ONUS 1
#define CPTCFG_CFG80211_DEBUGFS 1
#define CPTCFG_CFG80211_INTERNAL_REGDB 1
#define CPTCFG_CFG80211_WEXT 1
#define CPTCFG_LIB80211_MODULE 1
#define CPTCFG_LIB80211_CRYPT_WEP_MODULE 1
#define CPTCFG_LIB80211_CRYPT_CCMP_MODULE 1
#define CPTCFG_LIB80211_CRYPT_TKIP_MODULE 1
#define CPTCFG_MAC80211_MODULE 1
#define CPTCFG_MAC80211_HAS_RC 1
#define CPTCFG_MAC80211_RC_MINSTREL 1
#define CPTCFG_MAC80211_RC_MINSTREL_HT 1
#define CPTCFG_MAC80211_RC_DEFAULT_MINSTREL 1
#define CPTCFG_MAC80211_RC_DEFAULT "minstrel_ht"
#define CPTCFG_MAC80211_LEDS 1
#define CPTCFG_MAC80211_DEBUGFS 1
#define CPTCFG_WLAN 1
#define CPTCFG_MAC80211_HWSIM_MODULE 1
#define CPTCFG_LIBERTAS_MODULE 1
#define CPTCFG_LIBERTAS_SDIO_MODULE 1
#define CPTCFG_HERMES_MODULE 1
#define CPTCFG_HERMES_PRISM 1
#define CPTCFG_WL_TI 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
