.TH cgi_neo_error 3 "12 July 2007" "ClearSilver" "cgi/cgi.h"

.de Ss
.sp
.ft CW
.nf
..
.de Se
.fi
.ft P
.sp
..
.SH NAME
cgi_neo_error  - display a NEOERR call backtrace
.SH SYNOPSIS
.Ss
#include <cgi/cgi.h>
.Se
.Ss
void cgi_neo_error (CGI *cgi, NEOERR *err);

.Se

.SH ARGUMENTS
cgi - a pointer to a CGI struct
.br
err - a NEOERR (see util/neo_err.h for details)

.SH DESCRIPTION
cgi_neo_error will output a 500 error containing the
NEOERR call backtrace.  This function is likely to be
removed from future versions in favor of some sort of
user error mechanism.

.SH "RETURN VALUE"
None

.SH "SEE ALSO"
.BR cgi_debug_init "(3), "cgi_parse "(3), "cgi_destroy "(3), "cgi_js_escape "(3), "cgi_html_escape_strfunc "(3), "cgi_register_strfuncs "(3), "cgi_output "(3), "parse_rfc2388 "(3), "cgi_url_validate "(3), "open_upload "(3), "cgi_cs_init "(3), "cgi_url_escape_more "(3), "cgi_html_strip_strfunc "(3), "cgi_neo_error "(3), "cgi_redirect "(3), "cgi_filehandle "(3), "cgi_register_parse_cb "(3), "cgi_url_escape "(3), "cgi_init "(3), "cgi_redirect_uri "(3), "cgi_cookie_clear "(3), "cgi_url_unescape "(3), "cgi_vredirect "(3), "cgi_display "(3), "cgi_html_ws_strip "(3), "cgi_error "(3), "cgi_cookie_set "(3), "cgi_text_html_strfunc "(3), "cgi_cookie_authority
