.TH cgiwrap_writevf 3 "12 July 2007" "ClearSilver" "cgi/cgiwrap.h"

.de Ss
.sp
.ft CW
.nf
..
.de Se
.fi
.ft P
.sp
..
.SH NAME
cgiwrap_writevf  - a wrapper for vprintf
.SH SYNOPSIS
.Ss
#include <cgi/cgiwrap.h>
.Se
.Ss
NEOERR *cgiwrap_writevf (const char *fmt, va_list ap);

.Se

.SH ARGUMENTS
fmt - standard printf fmt string
.br
ap - stdarg argument pointer

.SH DESCRIPTION
cgiwrap_writevf is the formatted output command that
replaces vprintf or fvprintf(stdout) in a standard CGI
It is also used by cgiwrap_writef (the actual wrapped
function is a v type function)

.SH "RETURN VALUE"
None

.SH "SEE ALSO"
.BR cgiwrap_iterenv "(3), "cgiwrap_putenv "(3), "cgiwrap_init_emu "(3), "cgiwrap_writef "(3), "cgiwrap_init_std "(3), "cgiwrap_writevf "(3), "cgiwrap_read "(3), "cgiwrap_write "(3), "cgiwrap_getenv
