.TH cgiwrap_write 3 "12 July 2007" "ClearSilver" "cgi/cgiwrap.h"

.de Ss
.sp
.ft CW
.nf
..
.de Se
.fi
.ft P
.sp
..
.SH NAME
cgiwrap_write  - wrapper for the fwrite(stdout)
.SH SYNOPSIS
.Ss
#include <cgi/cgiwrap.h>
.Se
.Ss
NEOERR *cgiwrap_write (const char *buf, int buf_len);

.Se

.SH ARGUMENTS
buf - a character buffer
.br
buf_len - the length of the buffer in buf

.SH DESCRIPTION
cgiwrap_write is the block data output function for
cgiwrap that replaces fwrite(stdout) in regular CGIs

.SH "RETURN VALUE"
None

.SH "SEE ALSO"
.BR cgiwrap_iterenv "(3), "cgiwrap_putenv "(3), "cgiwrap_init_emu "(3), "cgiwrap_writef "(3), "cgiwrap_init_std "(3), "cgiwrap_writevf "(3), "cgiwrap_read "(3), "cgiwrap_write "(3), "cgiwrap_getenv
