.TH cs_register_esc_strfunc 3 "12 July 2007" "ClearSilver" "cs/cs.h"

.de Ss
.sp
.ft CW
.nf
..
.de Se
.fi
.ft P
.sp
..
.SH NAME
cs_register_esc_strfunc  - cs_register_strfunc with escaping context
.SH SYNOPSIS
.Ss
#include <cs/cs.h>
.Se
.Ss
NEOERR *cs_register_esc_strfunc(CSPARSE *parse, char *funcname,
                                CSSTRFUNC str_func);

.Se

.SH ARGUMENTS
parse - a pointer to a CSPARSE structure initialized with cs_init()
.br
funcname - the name for the CS function call
.br
Note that registering a duplicate funcname will
.br
raise a NERR_DUPLICATE error
.br
str_func - a CSSTRFUNC not-callback

.SH DESCRIPTION
cs_register_esc_strfunc functions exactly as cs_register_strfunc
except that it changes the evaluation escaping context to disable
default escaping.

.SH "SEE ALSO"
.BR cs_dump "(3), "cs_destroy "(3), "cs_render "(3), "cs_register_esc_strfunc "(3), "cs_arg_parsev "(3), "cs_register_fileload "(3), "cs_init "(3), "cs_register_strfunc "(3), "cs_arg_parse "(3), "cs_parse_string "(3), "cs_parse_file "(3), "= "(3), "cs_register_function
