.TH cWait 3 "12 July 2007" "ClearSilver" "util/ulocks.h"

.de Ss
.sp
.ft CW
.nf
..
.de Se
.fi
.ft P
.sp
..
.SH NAME
cWait  - wait a condition variable signal.
.SH SYNOPSIS
.Ss
#include <util/ulocks.h>
.Se
.Ss
NEOERR *cWait(pthread_cond_t *cond, pthread_mutex_t *mutex);

.Se

.SH ARGUMENTS
cond - condition variable to wait on.
.br
mutex - locked mutex to protect <cond>.

.SH DESCRIPTION
Waits for a signal on condition variable <cond>.
The mutex <mutex> must be locked by the thread.

MT-Level: Safe.

.SH "RETURN VALUE"
None.

.SH "SEE ALSO"
.BR mCreate "(3), "fCreate "(3), "mUnlock "(3), "fUnlock "(3), "cBroadcast "(3), "cSignal "(3), "fFind "(3), "cDestroy "(3), "cCreate "(3), "mDestroy "(3), "cWait "(3), "fLock "(3), "fDestroy "(3), "mLock
