.TH dictReleaseLock 3 "12 July 2007" "ClearSilver" "util/dict.h"

.de Ss
.sp
.ft CW
.nf
..
.de Se
.fi
.ft P
.sp
..
.SH NAME
dictReleaseLock  - release lock on value.
.SH SYNOPSIS
.Ss
#include <util/dict.h>
.Se
.Ss
void dictReleaseLock(dictCtx dict, void *lock);

.Se

.SH ARGUMENTS
dict - dictionary containing value to release.
.br
lock - lock to release.

.SH DESCRIPTION
Releases the lock on the value associated with <lock>.  Once
the lock is released, the dictCleanupFunc callback can
be called for the value (see dictCleanup()).

MT-Level: Safe if <dict> thread-safe.

.SH "RETURN VALUE"
None.

.SH "SEE ALSO"
.BR dictDestroy "(3), "dictCleanup "(3), "dictReleaseLock "(3), "dictRemove "(3), "dictNext "(3), "dictCreate "(3), "dictSetValue "(3), "dictModifyValue "(3), "dictSearch
