.TH fCreate 3 "12 July 2007" "ClearSilver" "util/ulocks.h"

.de Ss
.sp
.ft CW
.nf
..
.de Se
.fi
.ft P
.sp
..
.SH NAME
fCreate  - create a file lock.
.SH SYNOPSIS
.Ss
#include <util/ulocks.h>
.Se
.Ss
NEOERR *fCreate(int *plock, const char *file);

.Se

.SH ARGUMENTS
plock - place for lock.
.br
file - path of file to use as lock.

.SH DESCRIPTION
Creates a file lock on named file <file>.  The lock is
returned in <plock>.

MT-Level: Safe.

.SH "RETURN VALUE"
plock - set to lock identifier.

.SH "SEE ALSO"
.BR mCreate "(3), "fCreate "(3), "mUnlock "(3), "fUnlock "(3), "cBroadcast "(3), "cSignal "(3), "fFind "(3), "cDestroy "(3), "cCreate "(3), "mDestroy "(3), "cWait "(3), "fLock "(3), "fDestroy "(3), "mLock
