.TH skipInsert 3 "12 July 2007" "ClearSilver" "util/skiplist.h"

.de Ss
.sp
.ft CW
.nf
..
.de Se
.fi
.ft P
.sp
..
.SH NAME
skipInsert  - insert an item.
.SH SYNOPSIS
.Ss
#include <util/skiplist.h>
.Se
.Ss
NEOERR *skipInsert(skipList list, UINT32 key, void *value, int allowUpdate);

.Se

.SH ARGUMENTS
list - list to add pair to.
.br
key - key identifying <value>.
.br
value - value to store (may NOT be NULL)

.SH DESCRIPTION
Inserts the <key>/<value> pair into the <list>.
Key values 0 and -1 are reserved (and illegal).
If key is already in list, and <allowUpdate> is true, 
value is updated, otherwise SKIPERR_EXISTS is returned.

MT-Level: Safe if <list> thread-safe.

.SH "RETURN VALUE"
None.

.SH "SEE ALSO"
.BR skipDelete "(3), "skipFreeList "(3), "skipRelease "(3), "skipInsert "(3), "skipSearch "(3), "skipNext "(3), "skipNewList
