#! /bin/sh
# aoe-discover - trigger an AoE device discovery
# Copyright 2009, CORAID, Inc., and licensed under GPL v.2.

zero=`basename $0`
f=/dev/etherd/discover

if ! test -w $f; then
	echo 1>&2 $zero: $f does not exist or is not writeable.
	exit 1
fi
if ! test -c $f; then
	exec 1>&2
	echo "$zero: $f is not a character device file"
	echo "$zero: use udev or aoe-mkdevs to create it"
	exit 1
fi
echo > $f
