#! /bin/sh
# aoe-revalidate - ask aoe driver to query AoE target
# Copyright 2009, CORAID, Inc., and licensed under GPL v.2.

zero=`basename $0`
f=/dev/etherd/revalidate

if test -z "$*"; then
	echo 1>&2 Usage: $zero 'e{major}.{minor}'
	exit 1
fi
if ! test -w $f; then
	echo 1>&2 $zero: $f does not exist or is not writeable
	exit 1
fi
if ! test -c $f; then
	exec 1>&2
	echo "$zero: $f is not a character device file"
	echo "$zero: use udev or aoe-mkdevs to create it"
	exit 1
fi
echo "$*" > $f || {
	echo "$zero: revalidate failed" 1>&2
	exit 1
}

