#!/bin/sh

PDIR=$(pwd);
cd /usr/share/psybnc;
./psybnc "$@";
cd "$PDIR";

echo;
echo;
echo "Configuration is located at /usr/share/psybnc/psybnc.conf";
echo "everything can be configured within your chatclient,";
echo "after logging in as psybnc_admin ( /bhelp shows bnc help )";
